ip : 127.0.0.1

server:
  port: 8080
  context-path: /

web:
  upload-path : /Users/zhengwenzhan/Downloads
  load-path : /Users/zhengwenzhan/Downloads
  blogImg-path : /blogImg/

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${ip}:3306/blog
    username: wenzhan
    password: 1234
  thymeleaf:
    mode: HTML
    cache: false
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.load-path}
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wenzhan.blog.entity

jedis :
  pool :
    host : ${ip}
    port : 6379
    timeout : 60000
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000

qiniuyun :
  AK : 1980WcwMhP4B0OO2WfYKpfXcPRHXoHw27ZMgGK4e
  SK : s91HnJ7w_kngsXRA-gsLFnDMQfcnr4OnGp_wcC6o
  bucket : blog
  url : 127.0.0.1

github:
  GithubID :
  repo :
  ClientID :
  ClientSecret :


security:
  user:
    name: admin
    password: admin

logging:
  path: /home/caogen/project/blog/logs/

